export const START_AUTHENTICATION = 'START_AUTHENTICATION';
export const SUCCESS_AUTHENTICATION = 'SUCCESS_AUTHENTICATION';
export const FAILURE_AUTHENTICATION = 'FAILURE_AUTHENTICATION';
export const SET_SITE_DATA = 'SET_SITE_DATA';
export const LOGOUT = 'LOGOUT';
export const START_GET_USER_INFO = 'START_GET_USER_INFO';
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS';
export const GET_USER_INFO_FAILED = 'GET_USER_INFO_FAILED';

export const START_GET_NEWS = 'START_GET_NEWS';
export const GET_NEWS_SUCCESS = 'GET_NEWS_SUCCESS';
export const GET_NEWS_FAILED = 'GET_NEWS_FAILED';
